version: "2"
services:
  frontend:
    container_name: frontend
    image: task-notes-frontend
    ports:
      - "${PORT}:80"
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always