services:
  backend:
    container_name: backend
    image: task-notes-backend:${NODE_ENV}
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    command: >
      sh -c "
        npm install prisma &&
        npx prisma migrate deploy &&
        node dist/prisma/seed.js &&
        npm uninstall prisma &&
        npm run start:prod
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
